[mgr]
ratio = [1, 4, 3]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "size"

[preview]
wrap = "no"
image_filter = "triangle"
image_quality = 75

[opener]
edit = [
	{ run = '${EDITOR:-nvim} "$@"', block = true },
]

[open]
prepend_rules = [
	{ mime = "text/*", use = "edit" },
]
